// Demo data for when database is not connected
// Supports 4-phase client lifecycle:
// Phase 1: Client Onboarding
// Phase 2: Client Interactions
// Phase 3: Post-Contract Completion/Delivery
// Phase 4: Review & Feedback Collection

export const demoCompanies = [
  {
    id: 'demo-company-1',
    name: 'Acme Corporation',
    website: 'https://acme.com',
    industry: 'Technology',
    size: '51-200',
    phone: '+1 555-0001',
    address: '123 Tech Street',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    lifecycleStage: 'customer',
    customFields: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-company-2',
    name: 'Globex Industries',
    website: 'https://globex.com',
    industry: 'Manufacturing',
    size: '201-500',
    phone: '+1 555-0002',
    address: '456 Industrial Ave',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    lifecycleStage: 'lead',
    customFields: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-company-3',
    name: 'Initech Solutions',
    website: 'https://initech.io',
    industry: 'Software',
    size: '11-50',
    phone: '+1 555-0003',
    address: '789 Startup Blvd',
    city: 'Austin',
    state: 'TX',
    country: 'USA',
    lifecycleStage: 'lead',
    customFields: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoContacts = [
  {
    id: 'demo-contact-1',
    email: 'john.smith@acme.com',
    phone: '+1 555-0101',
    firstName: 'John',
    lastName: 'Smith',
    title: 'CEO',
    companyId: 'demo-company-1',
    lifecycleStage: 'customer',
    customFields: null,
    properties: null,
    lastActivityDate: new Date().toISOString(),
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-2',
    email: 'sarah.j@globex.com',
    phone: '+1 555-0102',
    firstName: 'Sarah',
    lastName: 'Johnson',
    title: 'VP of Sales',
    companyId: 'demo-company-2',
    lifecycleStage: 'sql',
    customFields: null,
    properties: null,
    lastActivityDate: new Date().toISOString(),
    company: demoCompanies[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-3',
    email: 'mike@initech.io',
    phone: '+1 555-0103',
    firstName: 'Mike',
    lastName: 'Davis',
    title: 'CTO',
    companyId: 'demo-company-3',
    lifecycleStage: 'mql',
    customFields: null,
    properties: null,
    lastActivityDate: new Date().toISOString(),
    company: demoCompanies[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-4',
    email: 'emily.brown@email.com',
    phone: '+1 555-0104',
    firstName: 'Emily',
    lastName: 'Brown',
    title: 'Freelance Consultant',
    companyId: null,
    lifecycleStage: 'lead',
    customFields: null,
    properties: null,
    lastActivityDate: null,
    company: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-5',
    email: 'alex.chen@acme.com',
    phone: '+1 555-0105',
    firstName: 'Alex',
    lastName: 'Chen',
    title: 'Product Manager',
    companyId: 'demo-company-1',
    lifecycleStage: 'sql',
    customFields: null,
    properties: null,
    lastActivityDate: new Date().toISOString(),
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Demo pipelines - Sales, Onboarding, and Delivery
export const demoPipelines = [
  {
    id: 'demo-pipeline-1',
    name: 'Sales Pipeline',
    type: 'sales',
    companyId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-pipeline-2',
    name: 'Client Onboarding',
    type: 'onboarding',
    companyId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-pipeline-3',
    name: 'Project Delivery',
    type: 'delivery',
    companyId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoPipelineStages = [
  // Sales Pipeline Stages
  { id: 'demo-stage-1', pipelineId: 'demo-pipeline-1', name: 'Discovery', sortOrder: 1 },
  { id: 'demo-stage-2', pipelineId: 'demo-pipeline-1', name: 'Proposal', sortOrder: 2 },
  { id: 'demo-stage-3', pipelineId: 'demo-pipeline-1', name: 'Negotiation', sortOrder: 3 },
  { id: 'demo-stage-4', pipelineId: 'demo-pipeline-1', name: 'Closed Won', sortOrder: 4 },
  { id: 'demo-stage-5', pipelineId: 'demo-pipeline-1', name: 'Closed Lost', sortOrder: 5 },
  // Onboarding Pipeline Stages
  { id: 'demo-stage-6', pipelineId: 'demo-pipeline-2', name: 'Welcome', sortOrder: 1 },
  { id: 'demo-stage-7', pipelineId: 'demo-pipeline-2', name: 'Documentation', sortOrder: 2 },
  { id: 'demo-stage-8', pipelineId: 'demo-pipeline-2', name: 'Setup & Configuration', sortOrder: 3 },
  { id: 'demo-stage-9', pipelineId: 'demo-pipeline-2', name: 'Training', sortOrder: 4 },
  { id: 'demo-stage-10', pipelineId: 'demo-pipeline-2', name: 'Go Live', sortOrder: 5 },
  // Delivery Pipeline Stages
  { id: 'demo-stage-11', pipelineId: 'demo-pipeline-3', name: 'Planning', sortOrder: 1 },
  { id: 'demo-stage-12', pipelineId: 'demo-pipeline-3', name: 'In Development', sortOrder: 2 },
  { id: 'demo-stage-13', pipelineId: 'demo-pipeline-3', name: 'Testing', sortOrder: 3 },
  { id: 'demo-stage-14', pipelineId: 'demo-pipeline-3', name: 'UAT', sortOrder: 4 },
  { id: 'demo-stage-15', pipelineId: 'demo-pipeline-3', name: 'Deployed', sortOrder: 5 },
];

export const demoDeals = [
  {
    id: 'demo-deal-1',
    name: 'Enterprise License Deal',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-3',
    stageName: 'Negotiation', // For UI display
    stage: 'negotiation', // For frontend Redux store
    amount: 150000,
    probability: 70,
    expectedCloseDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    properties: null,
    closedAt: null,
    company: demoCompanies[0],
    contact: demoContacts[0],
    pipelineStage: demoPipelineStages[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-2',
    name: 'Annual Support Contract',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-2',
    stageName: 'Proposal',
    stage: 'proposal',
    amount: 45000,
    probability: 50,
    expectedCloseDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    properties: null,
    closedAt: null,
    company: demoCompanies[1],
    contact: demoContacts[1],
    pipelineStage: demoPipelineStages[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-3',
    name: 'Consulting Project',
    companyId: 'demo-company-3',
    contactId: 'demo-contact-3',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-1',
    stageName: 'Discovery',
    stage: 'discovery',
    amount: 25000,
    probability: 30,
    expectedCloseDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    properties: null,
    closedAt: null,
    company: demoCompanies[2],
    contact: demoContacts[2],
    pipelineStage: demoPipelineStages[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-4',
    name: 'Q4 Expansion',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-4',
    stageName: 'Closed Won',
    stage: 'closed_won',
    amount: 80000,
    probability: 100,
    expectedCloseDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    properties: null,
    closedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    company: demoCompanies[0],
    contact: demoContacts[0],
    pipelineStage: demoPipelineStages[3],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-5',
    name: 'Lost Opportunity',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-5',
    stageName: 'Closed Lost',
    stage: 'closed_lost',
    amount: 35000,
    probability: 0,
    expectedCloseDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    properties: null,
    closedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    company: demoCompanies[1],
    contact: demoContacts[1],
    pipelineStage: demoPipelineStages[4],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoTasks = [
  {
    id: 'demo-task-1',
    title: 'Follow up on proposal',
    description: 'Send revised proposal with updated pricing',
    dealId: 'demo-deal-1',
    contactId: 'demo-contact-1',
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'high',
    status: 'open',
    completedAt: null,
    contact: demoContacts[0],
    deal: demoDeals[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-2',
    title: 'Schedule demo call',
    description: 'Coordinate with technical team for product demo',
    dealId: 'demo-deal-2',
    contactId: 'demo-contact-2',
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'medium',
    status: 'in_progress',
    completedAt: null,
    contact: demoContacts[1],
    deal: demoDeals[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-3',
    title: 'Send introduction email',
    description: 'Initial outreach completed',
    dealId: null,
    contactId: 'demo-contact-3',
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'low',
    status: 'completed',
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[2],
    deal: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-4',
    title: 'Prepare contract draft',
    description: 'Draft consulting agreement for legal review',
    dealId: 'demo-deal-3',
    contactId: null,
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'high',
    status: 'open',
    completedAt: null,
    contact: null,
    deal: demoDeals[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoActivities = [
  {
    id: 'demo-activity-1',
    type: 'note',
    entityType: 'deal',
    action: 'update',
    contactId: null,
    companyId: null,
    dealId: 'demo-deal-4',
    taskId: null,
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Deal moved to Closed Won',
    metadata: { from: 'Negotiation', to: 'Closed Won' },
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-2',
    type: 'note',
    entityType: 'contact',
    action: 'create',
    contactId: 'demo-contact-1',
    companyId: 'demo-company-1',
    dealId: null,
    taskId: null,
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Contact John Smith created',
    metadata: null,
    timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-3',
    type: 'task',
    entityType: 'task',
    action: 'update',
    contactId: 'demo-contact-3',
    companyId: null,
    dealId: null,
    taskId: 'demo-task-3',
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Task marked as completed',
    metadata: null,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-4',
    type: 'note',
    entityType: 'company',
    action: 'create',
    contactId: null,
    companyId: 'demo-company-1',
    dealId: null,
    taskId: null,
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Company Acme Corporation created',
    metadata: null,
    timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-5',
    type: 'note',
    entityType: 'deal',
    action: 'create',
    contactId: 'demo-contact-1',
    companyId: 'demo-company-1',
    dealId: 'demo-deal-1',
    taskId: null,
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Deal Enterprise License Deal created',
    metadata: null,
    timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-6',
    type: 'note',
    entityType: 'contact',
    action: 'update',
    contactId: 'demo-contact-2',
    companyId: 'demo-company-2',
    dealId: null,
    taskId: null,
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Contact Sarah Johnson lifecycle stage updated to SQL',
    metadata: { from: 'lead', to: 'sql' },
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-7',
    type: 'note',
    entityType: 'deal',
    action: 'delete',
    contactId: null,
    companyId: 'demo-company-2',
    dealId: 'demo-deal-5',
    taskId: null,
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Deal Lost Opportunity moved to Closed Lost',
    metadata: null,
    timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-8',
    type: 'task',
    entityType: 'task',
    action: 'create',
    contactId: 'demo-contact-1',
    companyId: null,
    dealId: 'demo-deal-1',
    taskId: 'demo-task-1',
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Task Follow up on proposal created',
    metadata: null,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-9',
    type: 'note',
    entityType: 'company',
    action: 'update',
    contactId: null,
    companyId: 'demo-company-1',
    dealId: null,
    taskId: null,
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Company Acme Corporation lifecycle stage updated to customer',
    metadata: { from: 'lead', to: 'customer' },
    timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-10',
    type: 'note',
    entityType: 'deal',
    action: 'update',
    contactId: 'demo-contact-2',
    companyId: 'demo-company-2',
    dealId: 'demo-deal-2',
    taskId: null,
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Deal Annual Support Contract moved to Proposal stage',
    metadata: { from: 'Discovery', to: 'Proposal' },
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Helper to get stage name from stageId
export const getStageNameById = (stageId: string): string => {
  const stage = demoPipelineStages.find(s => s.id === stageId);
  return stage?.name || 'Unknown';
};

// Helper to get deals by stage name (for backwards compatibility)
export const demoDealsByStage: Record<string, typeof demoDeals> = {
  discovery: demoDeals.filter(d => d.stage === 'discovery'),
  proposal: demoDeals.filter(d => d.stage === 'proposal'),
  negotiation: demoDeals.filter(d => d.stage === 'negotiation'),
  closed_won: demoDeals.filter(d => d.stage === 'closed_won'),
  closed_lost: demoDeals.filter(d => d.stage === 'closed_lost'),
};

// =====================
// Phase 1 & 3: Projects (Onboarding & Delivery)
// =====================
export const demoProjects = [
  {
    id: 'demo-project-1',
    name: 'Acme Corp Onboarding',
    description: 'Complete onboarding for Acme Corporation enterprise license',
    type: 'onboarding',
    status: 'in_progress',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    dealId: 'demo-deal-4',
    pipelineId: 'demo-pipeline-2',
    stageId: 'demo-stage-8',
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 60,
    metadata: { priority: 'high' },
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-2',
    name: 'Globex Custom Integration',
    description: 'Custom API integration project for Globex Industries',
    type: 'delivery',
    status: 'in_progress',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    dealId: null,
    pipelineId: 'demo-pipeline-3',
    stageId: 'demo-stage-12',
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 25,
    metadata: { priority: 'medium' },
    company: demoCompanies[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-3',
    name: 'Initech Implementation',
    description: 'Full implementation for Initech Solutions',
    type: 'implementation',
    status: 'not_started',
    companyId: 'demo-company-3',
    contactId: 'demo-contact-3',
    dealId: 'demo-deal-3',
    pipelineId: 'demo-pipeline-3',
    stageId: 'demo-stage-11',
    ownerId: 'demo-user-id',
    startDate: null,
    targetEndDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 0,
    metadata: null,
    company: demoCompanies[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Project Milestones
export const demoMilestones = [
  {
    id: 'demo-milestone-1',
    projectId: 'demo-project-1',
    name: 'Kickoff Meeting',
    description: 'Initial kickoff meeting with stakeholders',
    status: 'completed',
    dueDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 1,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-2',
    projectId: 'demo-project-1',
    name: 'Documentation Complete',
    description: 'All required documentation collected and verified',
    status: 'completed',
    dueDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 2,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-3',
    projectId: 'demo-project-1',
    name: 'System Configuration',
    description: 'Complete system setup and configuration',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 3,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-4',
    projectId: 'demo-project-1',
    name: 'User Training',
    description: 'Complete training for all users',
    status: 'pending',
    dueDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 4,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-5',
    projectId: 'demo-project-1',
    name: 'Go Live',
    description: 'Production deployment and go-live',
    status: 'pending',
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 5,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-6',
    projectId: 'demo-project-2',
    name: 'Requirements Gathering',
    description: 'Complete requirements gathering for integration',
    status: 'completed',
    dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 1,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-7',
    projectId: 'demo-project-2',
    name: 'API Development',
    description: 'Build custom API endpoints',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 2,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// =====================
// Phase 3: Tickets (Support/Issues)
// =====================
export const demoTickets = [
  {
    id: 'demo-ticket-1',
    title: 'API Integration Issue',
    description: 'Getting 401 errors when trying to authenticate with the API',
    type: 'bug',
    priority: 'high',
    status: 'in_progress',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    projectId: 'demo-project-1',
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    resolvedAt: null,
    closedAt: null,
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    metadata: { source: 'email' },
    company: demoCompanies[0],
    contact: demoContacts[0],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-ticket-2',
    title: 'Feature Request: Export to CSV',
    description: 'Would like ability to export reports to CSV format',
    type: 'feature_request',
    priority: 'medium',
    status: 'open',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    projectId: null,
    assignedTo: null,
    createdBy: 'demo-user-id',
    resolvedAt: null,
    closedAt: null,
    dueDate: null,
    metadata: { source: 'portal' },
    company: demoCompanies[1],
    contact: demoContacts[1],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-ticket-3',
    title: 'How to configure SSO?',
    description: 'Need guidance on setting up SSO with our identity provider',
    type: 'question',
    priority: 'low',
    status: 'waiting_on_client',
    companyId: 'demo-company-3',
    contactId: 'demo-contact-3',
    projectId: null,
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    resolvedAt: null,
    closedAt: null,
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    metadata: null,
    company: demoCompanies[2],
    contact: demoContacts[2],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-ticket-4',
    title: 'Performance issue resolved',
    description: 'Dashboard was loading slowly, optimized queries',
    type: 'support',
    priority: 'high',
    status: 'closed',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-5',
    projectId: null,
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    resolvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    closedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: null,
    metadata: { resolution: 'Query optimization' },
    company: demoCompanies[0],
    contact: demoContacts[4],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// =====================
// Phase 2: Email Templates & Sequences
// =====================
export const demoEmailTemplates = [
  {
    id: 'demo-template-1',
    name: 'Welcome Email',
    subjectTemplate: 'Welcome to {{company_name}}, {{first_name}}!',
    bodyTemplate: 'Dear {{first_name}},\n\nWelcome aboard! We\'re excited to have {{company_name}} as our newest customer.\n\nYour dedicated account manager will reach out within 24 hours to schedule your onboarding kickoff.\n\nBest regards,\nThe Team',
    variables: ['first_name', 'company_name'],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-template-2',
    name: 'Onboarding Checklist',
    subjectTemplate: 'Your Onboarding Checklist - {{company_name}}',
    bodyTemplate: 'Hi {{first_name}},\n\nHere\'s your onboarding checklist:\n\n1. Complete documentation\n2. Schedule training sessions\n3. Review system configuration\n4. Test integrations\n\nLet us know if you have any questions!\n\nBest,\nThe Team',
    variables: ['first_name', 'company_name'],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-template-3',
    name: 'Follow-up Email',
    subjectTemplate: 'Following up on our conversation',
    bodyTemplate: 'Hi {{first_name}},\n\nI wanted to follow up on our recent conversation about {{topic}}.\n\nPlease let me know if you have any questions or need additional information.\n\nBest regards,\n{{sender_name}}',
    variables: ['first_name', 'topic', 'sender_name'],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-template-4',
    name: 'NPS Survey Request',
    subjectTemplate: 'How are we doing? Quick 2-minute survey',
    bodyTemplate: 'Hi {{first_name}},\n\nWe\'d love to hear your feedback! Please take 2 minutes to complete our quick survey.\n\n{{survey_link}}\n\nYour input helps us improve.\n\nThank you!\nThe Team',
    variables: ['first_name', 'survey_link'],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-template-5',
    name: 'Project Milestone Update',
    subjectTemplate: 'Project Update: {{milestone_name}} Complete',
    bodyTemplate: 'Hi {{first_name}},\n\nGreat news! We\'ve completed the "{{milestone_name}}" milestone for your project.\n\nNext steps: {{next_steps}}\n\nCurrent progress: {{progress}}%\n\nBest regards,\nYour Project Team',
    variables: ['first_name', 'milestone_name', 'next_steps', 'progress'],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoEmailSequences = [
  {
    id: 'demo-sequence-1',
    name: 'New Customer Onboarding',
    description: 'Automated email sequence for new customers after deal is won',
    trigger: 'deal_won',
    status: 'active',
    companyId: null,
    createdBy: 'demo-user-id',
    metadata: { totalEmails: 4 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-sequence-2',
    name: 'Post-Onboarding Check-in',
    description: 'Follow-up sequence after onboarding is complete',
    trigger: 'milestone_complete',
    status: 'active',
    companyId: null,
    createdBy: 'demo-user-id',
    metadata: { triggerMilestone: 'Go Live' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-sequence-3',
    name: 'Quarterly Business Review',
    description: 'Quarterly check-in with customers',
    trigger: 'manual',
    status: 'active',
    companyId: null,
    createdBy: 'demo-user-id',
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoEmailSequenceSteps = [
  // Onboarding Sequence Steps
  {
    id: 'demo-step-1',
    sequenceId: 'demo-sequence-1',
    templateId: 'demo-template-1',
    stepType: 'email',
    delayDays: 0,
    delayHours: 0,
    sortOrder: 1,
    condition: null,
    metadata: null,
  },
  {
    id: 'demo-step-2',
    sequenceId: 'demo-sequence-1',
    templateId: null,
    stepType: 'delay',
    delayDays: 1,
    delayHours: 0,
    sortOrder: 2,
    condition: null,
    metadata: null,
  },
  {
    id: 'demo-step-3',
    sequenceId: 'demo-sequence-1',
    templateId: 'demo-template-2',
    stepType: 'email',
    delayDays: 0,
    delayHours: 0,
    sortOrder: 3,
    condition: null,
    metadata: null,
  },
  {
    id: 'demo-step-4',
    sequenceId: 'demo-sequence-1',
    templateId: null,
    stepType: 'delay',
    delayDays: 7,
    delayHours: 0,
    sortOrder: 4,
    condition: null,
    metadata: null,
  },
  {
    id: 'demo-step-5',
    sequenceId: 'demo-sequence-1',
    templateId: 'demo-template-3',
    stepType: 'email',
    delayDays: 0,
    delayHours: 0,
    sortOrder: 5,
    condition: null,
    metadata: null,
  },
  // Post-Onboarding Sequence Steps
  {
    id: 'demo-step-6',
    sequenceId: 'demo-sequence-2',
    templateId: 'demo-template-4',
    stepType: 'email',
    delayDays: 7,
    delayHours: 0,
    sortOrder: 1,
    condition: null,
    metadata: { description: 'Send NPS survey 7 days after go-live' },
  },
];

// =====================
// Phase 4: Surveys
// =====================
export const demoSurveys = [
  {
    id: 'demo-survey-1',
    name: 'Customer NPS Survey',
    type: 'NPS',
    status: 'active',
    questions: [
      {
        id: 'q1',
        type: 'nps',
        text: 'How likely are you to recommend us to a friend or colleague?',
        required: true,
      },
      {
        id: 'q2',
        type: 'text',
        text: 'What could we do to improve your experience?',
        required: false,
      },
    ],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-survey-2',
    name: 'Onboarding Satisfaction',
    type: 'CSAT',
    status: 'active',
    questions: [
      {
        id: 'q1',
        type: 'rating',
        text: 'How satisfied were you with the onboarding process?',
        scale: 5,
        required: true,
      },
      {
        id: 'q2',
        type: 'rating',
        text: 'How would you rate the quality of training provided?',
        scale: 5,
        required: true,
      },
      {
        id: 'q3',
        type: 'text',
        text: 'Any suggestions for improving our onboarding?',
        required: false,
      },
    ],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-survey-3',
    name: 'Support Effort Survey',
    type: 'CES',
    status: 'active',
    questions: [
      {
        id: 'q1',
        type: 'ces',
        text: 'How easy was it to get your issue resolved?',
        required: true,
      },
    ],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoSurveyResponses = [
  {
    id: 'demo-response-1',
    surveyId: 'demo-survey-1',
    contactId: 'demo-contact-1',
    companyId: 'demo-company-1',
    responses: {
      q1: 9,
      q2: 'Great service, very responsive team!',
    },
    score: 9,
    submittedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[0],
    company: demoCompanies[0],
  },
  {
    id: 'demo-response-2',
    surveyId: 'demo-survey-1',
    contactId: 'demo-contact-2',
    companyId: 'demo-company-2',
    responses: {
      q1: 7,
      q2: 'Would appreciate faster response times.',
    },
    score: 7,
    submittedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[1],
    company: demoCompanies[1],
  },
  {
    id: 'demo-response-3',
    surveyId: 'demo-survey-2',
    contactId: 'demo-contact-5',
    companyId: 'demo-company-1',
    responses: {
      q1: 5,
      q2: 4,
      q3: 'The training materials were very helpful.',
    },
    score: 4.5,
    submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[4],
    company: demoCompanies[0],
  },
];

// =====================
// Phase 4: Health Scores
// =====================
export const demoHealthScores = [
  {
    id: 'demo-health-1',
    companyId: 'demo-company-1',
    contactId: null,
    score: 85,
    npsScore: 9,
    csatScore: 4.5,
    cesScore: 6.2,
    customSurveyScore: 82,
    engagementScore: 90,
    riskLevel: 'excellent',
    calculatedAt: new Date().toISOString(),
    company: demoCompanies[0],
  },
  {
    id: 'demo-health-2',
    companyId: 'demo-company-2',
    contactId: null,
    score: 65,
    npsScore: 7,
    csatScore: null,
    cesScore: 4.5,
    customSurveyScore: 68,
    engagementScore: 60,
    riskLevel: 'caution',
    calculatedAt: new Date().toISOString(),
    company: demoCompanies[1],
  },
  {
    id: 'demo-health-3',
    companyId: 'demo-company-3',
    contactId: null,
    score: 45,
    npsScore: null,
    csatScore: null,
    cesScore: null,
    customSurveyScore: null,
    engagementScore: 40,
    riskLevel: 'at_risk',
    calculatedAt: new Date().toISOString(),
    company: demoCompanies[2],
  },
];

// =====================
// Phase 4: Automations
// =====================
export const demoAutomations = [
  {
    id: 'demo-automation-1',
    name: 'Welcome Email on Deal Won',
    triggerType: 'event',
    triggerConditions: {
      event: 'deal.stage_changed',
      toStage: 'Closed Won',
    },
    actions: [
      { type: 'start_sequence', sequenceId: 'demo-sequence-1' },
      { type: 'create_task', title: 'Schedule onboarding kickoff', assignTo: 'owner' },
    ],
    status: 'active',
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-automation-2',
    name: 'NPS Survey After Go-Live',
    triggerType: 'event',
    triggerConditions: {
      event: 'milestone.completed',
      milestoneName: 'Go Live',
    },
    actions: [
      { type: 'send_survey', surveyId: 'demo-survey-1', delay: '7d' },
    ],
    status: 'active',
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-automation-3',
    name: 'At-Risk Customer Alert',
    triggerType: 'event',
    triggerConditions: {
      event: 'health_score.below_threshold',
      threshold: 50,
    },
    actions: [
      { type: 'create_task', title: 'Review at-risk customer', assignTo: 'owner', priority: 'high' },
      { type: 'notify', channel: 'email', recipients: ['account_manager'] },
    ],
    status: 'active',
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-automation-4',
    name: 'Ticket SLA Warning',
    triggerType: 'time',
    triggerConditions: {
      entity: 'ticket',
      condition: 'due_date_approaching',
      hours: 24,
    },
    actions: [
      { type: 'notify', channel: 'email', recipients: ['assignee'] },
    ],
    status: 'active',
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// =====================
// Demo Emails (sent)
// =====================
export const demoEmails = [
  {
    id: 'demo-email-1',
    toEmail: 'john.smith@acme.com',
    subject: 'Welcome to Our Platform, John!',
    body: 'Dear John,\n\nWelcome aboard! We\'re excited to have Acme Corporation as our newest customer.\n\nYour dedicated account manager will reach out within 24 hours to schedule your onboarding kickoff.\n\nBest regards,\nThe Team',
    templateId: 'demo-template-1',
    contactId: 'demo-contact-1',
    dealId: 'demo-deal-4',
    sentBy: 'demo-user-id',
    sentAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    openedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 3600000).toISOString(),
    clickedAt: null,
    responseReceived: true,
    contact: demoContacts[0],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-email-2',
    toEmail: 'john.smith@acme.com',
    subject: 'Your Onboarding Checklist - Acme Corporation',
    body: 'Hi John,\n\nHere\'s your onboarding checklist:\n\n1. Complete documentation\n2. Schedule training sessions\n3. Review system configuration\n4. Test integrations\n\nLet us know if you have any questions!\n\nBest,\nThe Team',
    templateId: 'demo-template-2',
    contactId: 'demo-contact-1',
    dealId: null,
    sentBy: 'demo-user-id',
    sentAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    openedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000 + 7200000).toISOString(),
    clickedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000 + 7800000).toISOString(),
    responseReceived: false,
    contact: demoContacts[0],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Dynamic dashboard stats calculation
export const getDemoDashboardStats = () => {
  const today = new Date();
  const nextWeek = new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000);

  // Calculate pipeline value (non-closed deals)
  const pipelineDeals = demoDeals.filter(d => d.stage !== 'closed_won' && d.stage !== 'closed_lost');
  const pipelineValue = pipelineDeals.reduce((sum, d) => sum + (d.amount || 0), 0);

  // Calculate won/lost deals
  const wonDeals = demoDeals.filter(d => d.stage === 'closed_won');
  const lostDeals = demoDeals.filter(d => d.stage === 'closed_lost');
  const wonDealsValue = wonDeals.reduce((sum, d) => sum + (d.amount || 0), 0);
  const lostDealsValue = lostDeals.reduce((sum, d) => sum + (d.amount || 0), 0);
  const wonDealsCount = wonDeals.length;
  const lostDealsCount = lostDeals.length;
  const winRate = wonDealsCount + lostDealsCount > 0
    ? Math.round((wonDealsCount / (wonDealsCount + lostDealsCount)) * 100)
    : 0;

  // Calculate task metrics
  const openTasks = demoTasks.filter(t => t.status !== 'completed');
  const upcomingTasks = openTasks.filter(t => {
    if (!t.dueDate) return false;
    const dueDate = new Date(t.dueDate);
    return dueDate >= today && dueDate <= nextWeek;
  });
  const overdueTasks = openTasks.filter(t => {
    if (!t.dueDate) return false;
    return new Date(t.dueDate) < today;
  });

  // Calculate ticket metrics
  const openTickets = demoTickets.filter(t => t.status === 'open' || t.status === 'in_progress');
  const resolvedTickets = demoTickets.filter(t => t.status === 'closed' || t.status === 'resolved');

  return {
    // Sales metrics
    pipelineValue,
    wonDealsValue,
    lostDealsValue,
    wonDealsCount,
    lostDealsCount,
    winRate,
    // Entity counts
    totalCompanies: demoCompanies.length,
    totalContacts: demoContacts.length,
    totalDeals: demoDeals.length,
    totalTasks: demoTasks.length,
    totalProjects: demoProjects.length,
    totalTickets: demoTickets.length,
    // Task metrics
    upcomingTasksCount: upcomingTasks.length,
    overdueTasksCount: overdueTasks.length,
    // Ticket metrics
    openTicketsCount: openTickets.length,
    resolvedTicketsCount: resolvedTickets.length,
    avgTicketResolutionHours: 48,
    // Health metrics
    avgHealthScore: Math.round(demoHealthScores.reduce((sum, h) => sum + h.score, 0) / demoHealthScores.length),
    atRiskCustomers: demoHealthScores.filter(h => h.riskLevel === 'at_risk').length,
    // Survey metrics
    avgNpsScore: Math.round(demoSurveyResponses.filter(r => r.surveyId === 'demo-survey-1').reduce((sum, r) => sum + (r.score || 0), 0) / demoSurveyResponses.filter(r => r.surveyId === 'demo-survey-1').length) || 0,
    npsPromoters: demoSurveyResponses.filter(r => r.surveyId === 'demo-survey-1' && r.score >= 9).length,
    npsPassives: demoSurveyResponses.filter(r => r.surveyId === 'demo-survey-1' && r.score >= 7 && r.score < 9).length,
    npsDetractors: demoSurveyResponses.filter(r => r.surveyId === 'demo-survey-1' && r.score < 7).length,
    surveyResponseRate: 60,
  };
};

// For backwards compatibility
export const demoDashboardStats = getDemoDashboardStats();
