// Demo data for when database is not connected

export const demoCompanies = [
  {
    id: 'demo-company-1',
    name: 'Acme Corporation',
    domain: 'acme.com',
    industry: 'Technology',
    linkedinUrl: 'https://linkedin.com/company/acme',
    revenue: 5000000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-company-2',
    name: 'Globex Industries',
    domain: 'globex.com',
    industry: 'Manufacturing',
    linkedinUrl: 'https://linkedin.com/company/globex',
    revenue: 12000000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-company-3',
    name: 'Initech Solutions',
    domain: 'initech.io',
    industry: 'Software',
    linkedinUrl: null,
    revenue: 2500000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoContacts = [
  {
    id: 'demo-contact-1',
    companyId: 'demo-company-1',
    fullName: 'John Smith',
    email: 'john.smith@acme.com',
    phone: '+1 555-0101',
    jobTitle: 'CEO',
    lifecycleStage: 'customer',
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-2',
    companyId: 'demo-company-2',
    fullName: 'Sarah Johnson',
    email: 'sarah.j@globex.com',
    phone: '+1 555-0102',
    jobTitle: 'VP of Sales',
    lifecycleStage: 'sql',
    company: demoCompanies[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-3',
    companyId: 'demo-company-3',
    fullName: 'Mike Davis',
    email: 'mike@initech.io',
    phone: '+1 555-0103',
    jobTitle: 'CTO',
    lifecycleStage: 'mql',
    company: demoCompanies[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-4',
    companyId: null,
    fullName: 'Emily Brown',
    email: 'emily.brown@email.com',
    phone: '+1 555-0104',
    jobTitle: 'Freelance Consultant',
    lifecycleStage: 'lead',
    company: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-5',
    companyId: 'demo-company-1',
    fullName: 'Alex Chen',
    email: 'alex.chen@acme.com',
    phone: '+1 555-0105',
    jobTitle: 'Product Manager',
    lifecycleStage: 'sql',
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoDeals = [
  {
    id: 'demo-deal-1',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    name: 'Enterprise License Deal',
    amount: 150000,
    stage: 'negotiation',
    closeDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    probability: 70,
    company: demoCompanies[0],
    contact: demoContacts[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-2',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    name: 'Annual Support Contract',
    amount: 45000,
    stage: 'proposal',
    closeDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    probability: 50,
    company: demoCompanies[1],
    contact: demoContacts[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-3',
    companyId: 'demo-company-3',
    contactId: 'demo-contact-3',
    name: 'Consulting Project',
    amount: 25000,
    stage: 'discovery',
    closeDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    probability: 30,
    company: demoCompanies[2],
    contact: demoContacts[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-4',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    name: 'Q4 Expansion',
    amount: 80000,
    stage: 'closed_won',
    closeDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    probability: 100,
    company: demoCompanies[0],
    contact: demoContacts[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-5',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    name: 'Lost Opportunity',
    amount: 35000,
    stage: 'closed_lost',
    closeDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    probability: 0,
    company: demoCompanies[1],
    contact: demoContacts[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoTasks = [
  {
    id: 'demo-task-1',
    contactId: 'demo-contact-1',
    dealId: 'demo-deal-1',
    assignedTo: 'demo-user-id',
    name: 'Follow up on proposal',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'high',
    status: 'todo',
    description: 'Send revised proposal with updated pricing',
    contact: demoContacts[0],
    deal: demoDeals[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-2',
    contactId: 'demo-contact-2',
    dealId: 'demo-deal-2',
    assignedTo: 'demo-user-id',
    name: 'Schedule demo call',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'medium',
    status: 'in_progress',
    description: 'Coordinate with technical team for product demo',
    contact: demoContacts[1],
    deal: demoDeals[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-3',
    contactId: 'demo-contact-3',
    dealId: null,
    assignedTo: 'demo-user-id',
    name: 'Send introduction email',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'low',
    status: 'completed',
    description: 'Initial outreach completed',
    contact: demoContacts[2],
    deal: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-4',
    contactId: null,
    dealId: 'demo-deal-3',
    assignedTo: 'demo-user-id',
    name: 'Prepare contract draft',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'high',
    status: 'todo',
    description: 'Draft consulting agreement for legal review',
    contact: null,
    deal: demoDeals[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoActivities = [
  {
    id: 'demo-activity-1',
    entityType: 'deal',
    entityId: 'demo-deal-4',
    userId: 'demo-user-id',
    action: 'stage_changed',
    description: 'Deal moved to Closed Won',
    metadata: { from: 'negotiation', to: 'closed_won' },
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-2',
    entityType: 'contact',
    entityId: 'demo-contact-1',
    userId: 'demo-user-id',
    action: 'created',
    description: 'Contact created',
    metadata: null,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-3',
    entityType: 'task',
    entityId: 'demo-task-3',
    userId: 'demo-user-id',
    action: 'completed',
    description: 'Task marked as completed',
    metadata: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoDashboardStats = {
  pipelineValue: 220000,
  wonDealsValue: 80000,
  lostDealsValue: 35000,
  wonDealsCount: 1,
  lostDealsCount: 1,
  winRate: 50,
  totalCompanies: 3,
  totalContacts: 5,
  totalDeals: 5,
  totalTasks: 4,
  upcomingTasksCount: 3,
  overdueTasksCount: 0,
};

export const demoDealsByStage = {
  discovery: demoDeals.filter(d => d.stage === 'discovery'),
  proposal: demoDeals.filter(d => d.stage === 'proposal'),
  negotiation: demoDeals.filter(d => d.stage === 'negotiation'),
  closed_won: demoDeals.filter(d => d.stage === 'closed_won'),
  closed_lost: demoDeals.filter(d => d.stage === 'closed_lost'),
};
