// Demo data for when database is not connected
// Supports 4-phase client lifecycle:
// Phase 1: Client Onboarding
// Phase 2: Client Interactions
// Phase 3: Post-Contract Completion/Delivery
// Phase 4: Review & Feedback Collection

export const demoCompanies = [
  {
    id: 'demo-company-1',
    name: 'Acme Corporation',
    website: 'https://acme.com',
    industry: 'Technology',
    size: '51-200',
    phone: '+1 555-0001',
    address: '123 Tech Street',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    lifecycleStage: 'customer',
    customFields: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-company-2',
    name: 'Globex Industries',
    website: 'https://globex.com',
    industry: 'Manufacturing',
    size: '201-500',
    phone: '+1 555-0002',
    address: '456 Industrial Ave',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    lifecycleStage: 'lead',
    customFields: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-company-3',
    name: 'Initech Solutions',
    website: 'https://initech.io',
    industry: 'Software',
    size: '11-50',
    phone: '+1 555-0003',
    address: '789 Startup Blvd',
    city: 'Austin',
    state: 'TX',
    country: 'USA',
    lifecycleStage: 'lead',
    customFields: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoContacts = [
  {
    id: 'demo-contact-1',
    email: 'john.smith@acme.com',
    phone: '+1 555-0101',
    firstName: 'John',
    lastName: 'Smith',
    fullName: 'John Smith',
    title: 'CEO',
    jobTitle: 'CEO',
    companyId: 'demo-company-1',
    lifecycleStage: 'customer',
    customFields: null,
    properties: null,
    lastActivityDate: new Date().toISOString(),
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-2',
    email: 'sarah.j@globex.com',
    phone: '+1 555-0102',
    firstName: 'Sarah',
    lastName: 'Johnson',
    fullName: 'Sarah Johnson',
    title: 'VP of Sales',
    jobTitle: 'VP of Sales',
    companyId: 'demo-company-2',
    lifecycleStage: 'sql',
    customFields: null,
    properties: null,
    lastActivityDate: new Date().toISOString(),
    company: demoCompanies[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-3',
    email: 'mike@initech.io',
    phone: '+1 555-0103',
    firstName: 'Mike',
    lastName: 'Davis',
    fullName: 'Mike Davis',
    title: 'CTO',
    jobTitle: 'CTO',
    companyId: 'demo-company-3',
    lifecycleStage: 'mql',
    customFields: null,
    properties: null,
    lastActivityDate: new Date().toISOString(),
    company: demoCompanies[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-4',
    email: 'emily.brown@email.com',
    phone: '+1 555-0104',
    firstName: 'Emily',
    lastName: 'Brown',
    fullName: 'Emily Brown',
    title: 'Freelance Consultant',
    jobTitle: 'Freelance Consultant',
    companyId: null,
    lifecycleStage: 'lead',
    customFields: null,
    properties: null,
    lastActivityDate: null,
    company: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-contact-5',
    email: 'alex.chen@acme.com',
    phone: '+1 555-0105',
    firstName: 'Alex',
    lastName: 'Chen',
    fullName: 'Alex Chen',
    title: 'Product Manager',
    jobTitle: 'Product Manager',
    companyId: 'demo-company-1',
    lifecycleStage: 'sql',
    customFields: null,
    properties: null,
    lastActivityDate: new Date().toISOString(),
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Demo pipelines - Sales, Onboarding, and Delivery
export const demoPipelines = [
  {
    id: 'demo-pipeline-1',
    name: 'Sales Pipeline',
    type: 'sales',
    companyId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-pipeline-2',
    name: 'Client Onboarding',
    type: 'onboarding',
    companyId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-pipeline-3',
    name: 'Project Delivery',
    type: 'delivery',
    companyId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoPipelineStages = [
  // Sales Pipeline Stages
  { id: 'demo-stage-1', pipelineId: 'demo-pipeline-1', name: 'Discovery', sortOrder: 1, color: '#64748b' },
  { id: 'demo-stage-2', pipelineId: 'demo-pipeline-1', name: 'Proposal', sortOrder: 2, color: '#3b82f6' },
  { id: 'demo-stage-3', pipelineId: 'demo-pipeline-1', name: 'Negotiation', sortOrder: 3, color: '#f59e0b' },
  { id: 'demo-stage-4', pipelineId: 'demo-pipeline-1', name: 'Closed Won', sortOrder: 4, color: '#22c55e' },
  { id: 'demo-stage-5', pipelineId: 'demo-pipeline-1', name: 'Closed Lost', sortOrder: 5, color: '#ef4444' },
  // Onboarding Pipeline Stages
  { id: 'demo-stage-6', pipelineId: 'demo-pipeline-2', name: 'Welcome', sortOrder: 1, color: '#06b6d4' },
  { id: 'demo-stage-7', pipelineId: 'demo-pipeline-2', name: 'Documentation', sortOrder: 2, color: '#3b82f6' },
  { id: 'demo-stage-8', pipelineId: 'demo-pipeline-2', name: 'Setup & Configuration', sortOrder: 3, color: '#6366f1' },
  { id: 'demo-stage-9', pipelineId: 'demo-pipeline-2', name: 'Training', sortOrder: 4, color: '#a855f7' },
  { id: 'demo-stage-10', pipelineId: 'demo-pipeline-2', name: 'Go Live', sortOrder: 5, color: '#22c55e' },
  // Delivery Pipeline Stages
  { id: 'demo-stage-11', pipelineId: 'demo-pipeline-3', name: 'Planning', sortOrder: 1, color: '#64748b' },
  { id: 'demo-stage-12', pipelineId: 'demo-pipeline-3', name: 'In Development', sortOrder: 2, color: '#3b82f6' },
  { id: 'demo-stage-13', pipelineId: 'demo-pipeline-3', name: 'Testing', sortOrder: 3, color: '#f59e0b' },
  { id: 'demo-stage-14', pipelineId: 'demo-pipeline-3', name: 'UAT', sortOrder: 4, color: '#f97316' },
  { id: 'demo-stage-15', pipelineId: 'demo-pipeline-3', name: 'Deployed', sortOrder: 5, color: '#22c55e' },
];

export const demoDeals = [
  {
    id: 'demo-deal-1',
    name: 'Enterprise License Deal',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-3',
    stageName: 'Negotiation', // For UI display
    amount: 150000,
    probability: 70,
    expectedCloseDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    properties: null,
    closedAt: null,
    company: demoCompanies[0],
    contact: demoContacts[0],
    stage: demoPipelineStages[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-2',
    name: 'Annual Support Contract',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-2',
    stageName: 'Proposal',
    amount: 45000,
    probability: 50,
    expectedCloseDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    properties: null,
    closedAt: null,
    company: demoCompanies[1],
    contact: demoContacts[1],
    stage: demoPipelineStages[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-3',
    name: 'Consulting Project',
    companyId: 'demo-company-3',
    contactId: 'demo-contact-3',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-1',
    stageName: 'Discovery',
    amount: 25000,
    probability: 30,
    expectedCloseDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    properties: null,
    closedAt: null,
    company: demoCompanies[2],
    contact: demoContacts[2],
    stage: demoPipelineStages[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-4',
    name: 'Q4 Expansion',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-4',
    stageName: 'Closed Won',
    amount: 80000,
    probability: 100,
    expectedCloseDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    properties: null,
    closedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    company: demoCompanies[0],
    contact: demoContacts[0],
    stage: demoPipelineStages[3],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-deal-5',
    name: 'Lost Opportunity',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-5',
    stageName: 'Closed Lost',
    amount: 35000,
    probability: 0,
    expectedCloseDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    properties: null,
    closedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    company: demoCompanies[1],
    contact: demoContacts[1],
    stage: demoPipelineStages[4],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoTasks = [
  {
    id: 'demo-task-1',
    title: 'Follow up on proposal',
    name: 'Follow up on proposal',
    description: 'Send revised proposal with updated pricing',
    dealId: 'demo-deal-1',
    contactId: 'demo-contact-1',
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'high',
    status: 'todo',
    completedAt: null,
    contact: demoContacts[0],
    deal: demoDeals[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-2',
    title: 'Schedule demo call',
    name: 'Schedule demo call',
    description: 'Coordinate with technical team for product demo',
    dealId: 'demo-deal-2',
    contactId: 'demo-contact-2',
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'medium',
    status: 'in_progress',
    completedAt: null,
    contact: demoContacts[1],
    deal: demoDeals[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-3',
    title: 'Send introduction email',
    name: 'Send introduction email',
    description: 'Initial outreach completed',
    dealId: null,
    contactId: 'demo-contact-3',
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'low',
    status: 'completed',
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[2],
    deal: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-4',
    title: 'Prepare contract draft',
    name: 'Prepare contract draft',
    description: 'Draft consulting agreement for legal review',
    dealId: 'demo-deal-3',
    contactId: null,
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'high',
    status: 'todo',
    completedAt: null,
    contact: null,
    deal: demoDeals[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoActivities = [
  {
    id: 'demo-activity-1',
    type: 'note',
    contactId: null,
    companyId: null,
    dealId: 'demo-deal-4',
    taskId: null,
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Deal moved to Closed Won',
    metadata: { from: 'Negotiation', to: 'Closed Won' },
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-2',
    type: 'note',
    contactId: 'demo-contact-1',
    companyId: 'demo-company-1',
    dealId: null,
    taskId: null,
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Contact created',
    metadata: null,
    timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-activity-3',
    type: 'task',
    contactId: 'demo-contact-3',
    companyId: null,
    dealId: null,
    taskId: 'demo-task-3',
    emailId: null,
    createdBy: 'demo-user-id',
    description: 'Task marked as completed',
    metadata: null,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Helper to get stage name from stageId
export const getStageNameById = (stageId: string): string => {
  const stage = demoPipelineStages.find(s => s.id === stageId);
  return stage?.name || 'Unknown';
};

// Helper to get deals by stage name (for backwards compatibility)
export const demoDealsByStage = {
  discovery: demoDeals.filter(d => d.stageName === 'Discovery'),
  proposal: demoDeals.filter(d => d.stageName === 'Proposal'),
  negotiation: demoDeals.filter(d => d.stageName === 'Negotiation'),
  closed_won: demoDeals.filter(d => d.stageName === 'Closed Won'),
  closed_lost: demoDeals.filter(d => d.stageName === 'Closed Lost'),
};

// =====================
// Phase 1 & 3: Projects (Onboarding & Delivery)
// =====================
export const demoProjects = [
  {
    id: 'demo-project-1',
    name: 'Acme Corp Onboarding',
    description: 'Complete onboarding for Acme Corporation enterprise license',
    type: 'onboarding',
    status: 'in_progress',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    dealId: 'demo-deal-4',
    pipelineId: 'demo-pipeline-2',
    stageId: 'demo-stage-8',
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 60,
    metadata: { priority: 'high' },
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-2',
    name: 'Globex Custom Integration',
    description: 'Custom API integration project for Globex Industries',
    type: 'delivery',
    status: 'in_progress',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    dealId: null,
    pipelineId: 'demo-pipeline-3',
    stageId: 'demo-stage-12',
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 25,
    metadata: { priority: 'medium' },
    company: demoCompanies[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-3',
    name: 'Initech Implementation',
    description: 'Full implementation for Initech Solutions',
    type: 'implementation',
    status: 'not_started',
    companyId: 'demo-company-3',
    contactId: 'demo-contact-3',
    dealId: 'demo-deal-3',
    pipelineId: 'demo-pipeline-3',
    stageId: 'demo-stage-11',
    ownerId: 'demo-user-id',
    startDate: null,
    targetEndDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 0,
    metadata: null,
    company: demoCompanies[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // New unique projects
  {
    id: 'demo-project-4',
    name: 'Mobile App Development',
    description: 'Native iOS and Android app development for customer portal access',
    type: 'delivery',
    status: 'in_progress',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-5',
    dealId: null,
    pipelineId: 'demo-pipeline-3',
    stageId: 'demo-stage-13', // Testing
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 75,
    metadata: { priority: 'high', techStack: ['React Native', 'TypeScript'] },
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-5',
    name: 'Cloud Migration Initiative',
    description: 'Migrate legacy infrastructure to AWS cloud with zero downtime',
    type: 'delivery',
    status: 'in_progress',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    dealId: null,
    pipelineId: 'demo-pipeline-3',
    stageId: 'demo-stage-14', // UAT
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 88,
    metadata: { priority: 'critical', cloudProvider: 'AWS' },
    company: demoCompanies[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-6',
    name: 'Analytics Dashboard v2.0',
    description: 'Next-gen business intelligence dashboard with real-time metrics',
    type: 'delivery',
    status: 'completed',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    dealId: null,
    pipelineId: 'demo-pipeline-3',
    stageId: 'demo-stage-15', // Deployed
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    progress: 100,
    metadata: { priority: 'medium', features: ['Real-time', 'Export', 'Custom widgets'] },
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-7',
    name: 'E-commerce Platform Launch',
    description: 'Full-stack e-commerce solution with inventory management',
    type: 'delivery',
    status: 'in_progress',
    companyId: 'demo-company-3',
    contactId: 'demo-contact-3',
    dealId: null,
    pipelineId: 'demo-pipeline-3',
    stageId: 'demo-stage-12', // In Development
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 35,
    metadata: { priority: 'high', paymentGateway: 'Stripe' },
    company: demoCompanies[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-8',
    name: 'Enterprise Security Audit',
    description: 'Comprehensive security assessment and compliance certification',
    type: 'delivery',
    status: 'in_progress',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    dealId: null,
    pipelineId: 'demo-pipeline-3',
    stageId: 'demo-stage-13', // Testing
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 55,
    metadata: { priority: 'critical', compliance: ['SOC2', 'ISO27001'] },
    company: demoCompanies[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-9',
    name: 'Globex Premium Onboarding',
    description: 'White-glove onboarding experience for enterprise tier',
    type: 'onboarding',
    status: 'in_progress',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    dealId: null,
    pipelineId: 'demo-pipeline-2',
    stageId: 'demo-stage-9', // Training
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 70,
    metadata: { priority: 'high', tier: 'Enterprise' },
    company: demoCompanies[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-10',
    name: 'Data Migration Project',
    description: 'Migrate 5 years of historical data from legacy CRM system',
    type: 'delivery',
    status: 'in_progress',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    dealId: null,
    pipelineId: 'demo-pipeline-3',
    stageId: 'demo-stage-11', // Planning
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 10,
    metadata: { priority: 'medium', recordCount: '500000+' },
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-11',
    name: 'Initech Quick Start',
    description: 'Streamlined onboarding for startup tier customers',
    type: 'onboarding',
    status: 'in_progress',
    companyId: 'demo-company-3',
    contactId: 'demo-contact-3',
    dealId: null,
    pipelineId: 'demo-pipeline-2',
    stageId: 'demo-stage-7', // Documentation
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 40,
    metadata: { priority: 'medium', tier: 'Startup' },
    company: demoCompanies[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-12',
    name: 'UI/UX Redesign Sprint',
    description: 'Complete visual overhaul with new design system implementation',
    type: 'delivery',
    status: 'completed',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-5',
    dealId: null,
    pipelineId: 'demo-pipeline-3',
    stageId: 'demo-stage-15', // Deployed
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    progress: 100,
    metadata: { priority: 'medium', designSystem: 'Tailwind + Radix' },
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-13',
    name: 'Acme Welcome Package',
    description: 'New department onboarding for Acme expansion team',
    type: 'onboarding',
    status: 'in_progress',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-5',
    dealId: null,
    pipelineId: 'demo-pipeline-2',
    stageId: 'demo-stage-6', // Welcome
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 5,
    metadata: { priority: 'medium', newUsers: 15 },
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Sales Pipeline Projects (linked to deals)
  {
    id: 'demo-project-14',
    name: 'Enterprise License POC',
    description: 'Proof of concept for Acme Corporation enterprise license deal',
    type: 'sales',
    status: 'in_progress',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    dealId: 'demo-deal-1',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-3', // Negotiation
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 70,
    metadata: { priority: 'high', dealValue: 150000 },
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-15',
    name: 'Globex Support Proposal',
    description: 'Annual support contract proposal preparation for Globex Industries',
    type: 'sales',
    status: 'in_progress',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    dealId: 'demo-deal-2',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-2', // Proposal
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 45,
    metadata: { priority: 'medium', dealValue: 45000 },
    company: demoCompanies[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-16',
    name: 'Initech Discovery Assessment',
    description: 'Initial discovery and requirements gathering for consulting project',
    type: 'sales',
    status: 'in_progress',
    companyId: 'demo-company-3',
    contactId: 'demo-contact-3',
    dealId: 'demo-deal-3',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-1', // Discovery
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 20,
    metadata: { priority: 'medium', dealValue: 25000 },
    company: demoCompanies[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-17',
    name: 'Q4 Expansion Rollout',
    description: 'Successful expansion project for Acme Corporation - closed won',
    type: 'sales',
    status: 'completed',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    dealId: 'demo-deal-4',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-4', // Closed Won
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    progress: 100,
    metadata: { priority: 'high', dealValue: 80000, outcome: 'won' },
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-18',
    name: 'Globex Premium Upgrade',
    description: 'Lost opportunity - competitor selected',
    type: 'sales',
    status: 'completed',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    dealId: 'demo-deal-5',
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-5', // Closed Lost
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    progress: 100,
    metadata: { priority: 'medium', dealValue: 35000, outcome: 'lost', reason: 'Competitor pricing' },
    company: demoCompanies[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-19',
    name: 'Acme Analytics Upsell',
    description: 'New analytics module upsell opportunity in negotiation',
    type: 'sales',
    status: 'in_progress',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-5',
    dealId: null,
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-3', // Negotiation
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 60,
    metadata: { priority: 'high', estimatedValue: 55000 },
    company: demoCompanies[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-project-20',
    name: 'Initech Starter Package',
    description: 'Entry-level package proposal for Initech startup tier',
    type: 'sales',
    status: 'in_progress',
    companyId: 'demo-company-3',
    contactId: 'demo-contact-3',
    dealId: null,
    pipelineId: 'demo-pipeline-1',
    stageId: 'demo-stage-2', // Proposal
    ownerId: 'demo-user-id',
    startDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    targetEndDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    actualEndDate: null,
    progress: 35,
    metadata: { priority: 'medium', estimatedValue: 15000 },
    company: demoCompanies[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Project Milestones
export const demoMilestones = [
  {
    id: 'demo-milestone-1',
    projectId: 'demo-project-1',
    name: 'Kickoff Meeting',
    description: 'Initial kickoff meeting with stakeholders',
    status: 'completed',
    dueDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 1,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-2',
    projectId: 'demo-project-1',
    name: 'Documentation Complete',
    description: 'All required documentation collected and verified',
    status: 'completed',
    dueDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 2,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-3',
    projectId: 'demo-project-1',
    name: 'System Configuration',
    description: 'Complete system setup and configuration',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 3,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-4',
    projectId: 'demo-project-1',
    name: 'User Training',
    description: 'Complete training for all users',
    status: 'pending',
    dueDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 4,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-5',
    projectId: 'demo-project-1',
    name: 'Go Live',
    description: 'Production deployment and go-live',
    status: 'pending',
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 5,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-6',
    projectId: 'demo-project-2',
    name: 'Requirements Gathering',
    description: 'Complete requirements gathering for integration',
    status: 'completed',
    dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 1,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-7',
    projectId: 'demo-project-2',
    name: 'API Development',
    description: 'Build custom API endpoints',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 2,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Milestones for Mobile App Development (project-4)
  {
    id: 'demo-milestone-8',
    projectId: 'demo-project-4',
    name: 'App Architecture Design',
    description: 'Define app structure and component hierarchy',
    status: 'completed',
    dueDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 1,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-9',
    projectId: 'demo-project-4',
    name: 'Core Features Development',
    description: 'Implement authentication, navigation, and API integration',
    status: 'completed',
    dueDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 2,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-10',
    projectId: 'demo-project-4',
    name: 'QA Testing & Bug Fixes',
    description: 'Complete comprehensive testing across iOS and Android',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 3,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-11',
    projectId: 'demo-project-4',
    name: 'App Store Submission',
    description: 'Submit to Apple App Store and Google Play',
    status: 'pending',
    dueDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 4,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Milestones for Cloud Migration (project-5)
  {
    id: 'demo-milestone-12',
    projectId: 'demo-project-5',
    name: 'Infrastructure Assessment',
    description: 'Audit current infrastructure and create migration plan',
    status: 'completed',
    dueDate: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 1,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-13',
    projectId: 'demo-project-5',
    name: 'AWS Environment Setup',
    description: 'Configure VPC, security groups, and managed services',
    status: 'completed',
    dueDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 2,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-14',
    projectId: 'demo-project-5',
    name: 'Data Migration',
    description: 'Migrate databases and storage to cloud',
    status: 'completed',
    dueDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 3,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-15',
    projectId: 'demo-project-5',
    name: 'UAT & Performance Testing',
    description: 'User acceptance testing and load testing',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 4,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-16',
    projectId: 'demo-project-5',
    name: 'Production Cutover',
    description: 'Final migration and DNS switch',
    status: 'pending',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 5,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Milestones for E-commerce Platform (project-7)
  {
    id: 'demo-milestone-17',
    projectId: 'demo-project-7',
    name: 'Product Catalog Setup',
    description: 'Design and implement product data model',
    status: 'completed',
    dueDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 1,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-18',
    projectId: 'demo-project-7',
    name: 'Shopping Cart & Checkout',
    description: 'Implement cart functionality and Stripe integration',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 2,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-19',
    projectId: 'demo-project-7',
    name: 'Inventory Management',
    description: 'Build inventory tracking and alerts system',
    status: 'pending',
    dueDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 3,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Milestones for Security Audit (project-8)
  {
    id: 'demo-milestone-20',
    projectId: 'demo-project-8',
    name: 'Vulnerability Assessment',
    description: 'Automated and manual security scanning',
    status: 'completed',
    dueDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 1,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-21',
    projectId: 'demo-project-8',
    name: 'Penetration Testing',
    description: 'Simulated attacks and exploitation attempts',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 2,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-22',
    projectId: 'demo-project-8',
    name: 'Compliance Documentation',
    description: 'Prepare SOC2 and ISO27001 evidence',
    status: 'pending',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 3,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Milestones for Sales Pipeline - Enterprise License POC (project-14)
  {
    id: 'demo-milestone-23',
    projectId: 'demo-project-14',
    name: 'Technical Discovery Call',
    description: 'Initial technical requirements gathering with stakeholders',
    status: 'completed',
    dueDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 1,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-24',
    projectId: 'demo-project-14',
    name: 'POC Environment Setup',
    description: 'Configure sandbox environment for client testing',
    status: 'completed',
    dueDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 2,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-25',
    projectId: 'demo-project-14',
    name: 'POC Demo & Feedback',
    description: 'Present POC results and gather client feedback',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 3,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-26',
    projectId: 'demo-project-14',
    name: 'Final Proposal Submission',
    description: 'Submit final pricing and implementation proposal',
    status: 'pending',
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 4,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Milestones for Sales Pipeline - Globex Support Proposal (project-15)
  {
    id: 'demo-milestone-27',
    projectId: 'demo-project-15',
    name: 'Requirements Workshop',
    description: 'Conduct support requirements workshop with client team',
    status: 'completed',
    dueDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 1,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-28',
    projectId: 'demo-project-15',
    name: 'Draft Proposal Review',
    description: 'Internal review of support contract proposal',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 2,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-29',
    projectId: 'demo-project-15',
    name: 'Client Presentation',
    description: 'Present proposal and negotiate terms',
    status: 'pending',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 3,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Milestones for Sales Pipeline - Initech Discovery (project-16)
  {
    id: 'demo-milestone-30',
    projectId: 'demo-project-16',
    name: 'Initial Contact',
    description: 'First meeting with Initech leadership',
    status: 'completed',
    dueDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    sortOrder: 1,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-31',
    projectId: 'demo-project-16',
    name: 'Needs Assessment',
    description: 'Comprehensive needs assessment questionnaire',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 2,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-milestone-32',
    projectId: 'demo-project-16',
    name: 'Solution Fit Analysis',
    description: 'Analyze solution fit and prepare recommendations',
    status: 'pending',
    dueDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: null,
    sortOrder: 3,
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// =====================
// Phase 3: Tickets (Support/Issues)
// =====================
export const demoTickets = [
  {
    id: 'demo-ticket-1',
    title: 'API Integration Issue',
    description: 'Getting 401 errors when trying to authenticate with the API',
    type: 'bug',
    priority: 'high',
    status: 'in_progress',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-1',
    projectId: 'demo-project-1',
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    resolvedAt: null,
    closedAt: null,
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    metadata: { source: 'email' },
    company: demoCompanies[0],
    contact: demoContacts[0],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-ticket-2',
    title: 'Feature Request: Export to CSV',
    description: 'Would like ability to export reports to CSV format',
    type: 'feature_request',
    priority: 'medium',
    status: 'open',
    companyId: 'demo-company-2',
    contactId: 'demo-contact-2',
    projectId: null,
    assignedTo: null,
    createdBy: 'demo-user-id',
    resolvedAt: null,
    closedAt: null,
    dueDate: null,
    metadata: { source: 'portal' },
    company: demoCompanies[1],
    contact: demoContacts[1],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-ticket-3',
    title: 'How to configure SSO?',
    description: 'Need guidance on setting up SSO with our identity provider',
    type: 'question',
    priority: 'low',
    status: 'waiting_on_client',
    companyId: 'demo-company-3',
    contactId: 'demo-contact-3',
    projectId: null,
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    resolvedAt: null,
    closedAt: null,
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    metadata: null,
    company: demoCompanies[2],
    contact: demoContacts[2],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-ticket-4',
    title: 'Performance issue resolved',
    description: 'Dashboard was loading slowly, optimized queries',
    type: 'support',
    priority: 'high',
    status: 'closed',
    companyId: 'demo-company-1',
    contactId: 'demo-contact-5',
    projectId: null,
    assignedTo: 'demo-user-id',
    createdBy: 'demo-user-id',
    resolvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    closedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: null,
    metadata: { resolution: 'Query optimization' },
    company: demoCompanies[0],
    contact: demoContacts[4],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// =====================
// Phase 2: Email Templates & Sequences
// =====================
export const demoEmailTemplates = [
  {
    id: 'demo-template-1',
    name: 'Welcome Email',
    subjectTemplate: 'Welcome to {{company_name}}, {{first_name}}!',
    bodyTemplate: 'Dear {{first_name}},\n\nWelcome aboard! We\'re excited to have {{company_name}} as our newest customer.\n\nYour dedicated account manager will reach out within 24 hours to schedule your onboarding kickoff.\n\nBest regards,\nThe Team',
    variables: ['first_name', 'company_name'],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-template-2',
    name: 'Onboarding Checklist',
    subjectTemplate: 'Your Onboarding Checklist - {{company_name}}',
    bodyTemplate: 'Hi {{first_name}},\n\nHere\'s your onboarding checklist:\n\n1. Complete documentation\n2. Schedule training sessions\n3. Review system configuration\n4. Test integrations\n\nLet us know if you have any questions!\n\nBest,\nThe Team',
    variables: ['first_name', 'company_name'],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-template-3',
    name: 'Follow-up Email',
    subjectTemplate: 'Following up on our conversation',
    bodyTemplate: 'Hi {{first_name}},\n\nI wanted to follow up on our recent conversation about {{topic}}.\n\nPlease let me know if you have any questions or need additional information.\n\nBest regards,\n{{sender_name}}',
    variables: ['first_name', 'topic', 'sender_name'],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-template-4',
    name: 'NPS Survey Request',
    subjectTemplate: 'How are we doing? Quick 2-minute survey',
    bodyTemplate: 'Hi {{first_name}},\n\nWe\'d love to hear your feedback! Please take 2 minutes to complete our quick survey.\n\n{{survey_link}}\n\nYour input helps us improve.\n\nThank you!\nThe Team',
    variables: ['first_name', 'survey_link'],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-template-5',
    name: 'Project Milestone Update',
    subjectTemplate: 'Project Update: {{milestone_name}} Complete',
    bodyTemplate: 'Hi {{first_name}},\n\nGreat news! We\'ve completed the "{{milestone_name}}" milestone for your project.\n\nNext steps: {{next_steps}}\n\nCurrent progress: {{progress}}%\n\nBest regards,\nYour Project Team',
    variables: ['first_name', 'milestone_name', 'next_steps', 'progress'],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoEmailSequences = [
  {
    id: 'demo-sequence-1',
    name: 'New Customer Onboarding',
    description: 'Automated email sequence for new customers after deal is won',
    trigger: 'deal_won',
    status: 'active',
    companyId: null,
    createdBy: 'demo-user-id',
    metadata: { totalEmails: 4 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-sequence-2',
    name: 'Post-Onboarding Check-in',
    description: 'Follow-up sequence after onboarding is complete',
    trigger: 'milestone_complete',
    status: 'active',
    companyId: null,
    createdBy: 'demo-user-id',
    metadata: { triggerMilestone: 'Go Live' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-sequence-3',
    name: 'Quarterly Business Review',
    description: 'Quarterly check-in with customers',
    trigger: 'manual',
    status: 'active',
    companyId: null,
    createdBy: 'demo-user-id',
    metadata: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoEmailSequenceSteps = [
  // Onboarding Sequence Steps
  {
    id: 'demo-step-1',
    sequenceId: 'demo-sequence-1',
    templateId: 'demo-template-1',
    stepType: 'email',
    delayDays: 0,
    delayHours: 0,
    sortOrder: 1,
    condition: null,
    metadata: null,
  },
  {
    id: 'demo-step-2',
    sequenceId: 'demo-sequence-1',
    templateId: null,
    stepType: 'delay',
    delayDays: 1,
    delayHours: 0,
    sortOrder: 2,
    condition: null,
    metadata: null,
  },
  {
    id: 'demo-step-3',
    sequenceId: 'demo-sequence-1',
    templateId: 'demo-template-2',
    stepType: 'email',
    delayDays: 0,
    delayHours: 0,
    sortOrder: 3,
    condition: null,
    metadata: null,
  },
  {
    id: 'demo-step-4',
    sequenceId: 'demo-sequence-1',
    templateId: null,
    stepType: 'delay',
    delayDays: 7,
    delayHours: 0,
    sortOrder: 4,
    condition: null,
    metadata: null,
  },
  {
    id: 'demo-step-5',
    sequenceId: 'demo-sequence-1',
    templateId: 'demo-template-3',
    stepType: 'email',
    delayDays: 0,
    delayHours: 0,
    sortOrder: 5,
    condition: null,
    metadata: null,
  },
  // Post-Onboarding Sequence Steps
  {
    id: 'demo-step-6',
    sequenceId: 'demo-sequence-2',
    templateId: 'demo-template-4',
    stepType: 'email',
    delayDays: 7,
    delayHours: 0,
    sortOrder: 1,
    condition: null,
    metadata: { description: 'Send NPS survey 7 days after go-live' },
  },
];

// =====================
// Phase 4: Surveys
// =====================
export const demoSurveys = [
  {
    id: 'demo-survey-1',
    name: 'Customer NPS Survey',
    description: 'Monthly Net Promoter Score survey to measure customer loyalty and satisfaction',
    type: 'nps',
    status: 'active',
    triggerEvent: 'project_completed',
    sendAfterDays: 7,
    questions: [
      {
        id: 'q1',
        type: 'rating',
        text: 'How likely are you to recommend us to a friend or colleague?',
        scale: 10,
        required: true,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        text: 'What aspect of our service do you value most?',
        options: ['Product Quality', 'Customer Support', 'Pricing', 'Ease of Use', 'Reliability'],
        required: true,
      },
      {
        id: 'q3',
        type: 'yes_no',
        text: 'Would you use our services again?',
        required: true,
      },
      {
        id: 'q4',
        type: 'text',
        text: 'What could we do to improve your experience?',
        required: false,
      },
    ],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-survey-2',
    name: 'Onboarding Satisfaction',
    description: 'Survey to evaluate the customer onboarding experience and identify improvement areas',
    type: 'csat',
    status: 'active',
    triggerEvent: 'milestone_completed',
    sendAfterDays: 1,
    questions: [
      {
        id: 'q1',
        type: 'rating',
        text: 'How satisfied were you with the onboarding process?',
        scale: 5,
        required: true,
      },
      {
        id: 'q2',
        type: 'rating',
        text: 'How would you rate the quality of training provided?',
        scale: 5,
        required: true,
      },
      {
        id: 'q3',
        type: 'yes_no',
        text: 'Did the onboarding meet your expectations?',
        required: true,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        text: 'Which onboarding resource was most helpful?',
        options: ['Documentation', 'Video Tutorials', 'Live Training Sessions', 'Support Team'],
        required: true,
      },
      {
        id: 'q5',
        type: 'text',
        text: 'Any suggestions for improving our onboarding?',
        required: false,
      },
    ],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-survey-3',
    name: 'Support Experience Survey',
    description: 'Customer Effort Score survey to measure support ticket resolution experience',
    type: 'ces',
    status: 'active',
    triggerEvent: 'ticket_resolved',
    sendAfterDays: 0,
    questions: [
      {
        id: 'q1',
        type: 'rating',
        text: 'How easy was it to get your issue resolved?',
        scale: 7,
        required: true,
      },
      {
        id: 'q2',
        type: 'yes_no',
        text: 'Was your issue fully resolved?',
        required: true,
      },
      {
        id: 'q3',
        type: 'rating',
        text: 'How would you rate the support agent\'s helpfulness?',
        scale: 5,
        required: true,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        text: 'How did you contact support?',
        options: ['Email', 'Phone', 'Live Chat', 'Support Ticket'],
        required: true,
      },
      {
        id: 'q5',
        type: 'text',
        text: 'Any additional feedback about your support experience?',
        required: false,
      },
    ],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-survey-4',
    name: 'Product Feedback Survey',
    description: 'Custom survey to gather detailed product feedback and feature requests',
    type: 'custom',
    status: 'active',
    triggerEvent: '',
    sendAfterDays: 0,
    questions: [
      {
        id: 'q1',
        type: 'rating',
        text: 'Overall, how satisfied are you with our product?',
        scale: 10,
        required: true,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        text: 'Which feature do you use most frequently?',
        options: ['Dashboard Analytics', 'Deal Management', 'Project Tracking', 'Contact Management', 'Reporting'],
        required: true,
      },
      {
        id: 'q3',
        type: 'yes_no',
        text: 'Have you encountered any bugs or issues recently?',
        required: true,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        text: 'What new feature would you like to see?',
        options: ['Mobile App', 'AI Insights', 'Advanced Reporting', 'More Integrations', 'Workflow Automation'],
        required: false,
      },
      {
        id: 'q5',
        type: 'text',
        text: 'Please share any detailed feedback or feature requests',
        required: false,
      },
    ],
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoSurveyResponses = [
  // NPS Survey Responses
  {
    id: 'demo-response-1',
    surveyId: 'demo-survey-1',
    contactId: 'demo-contact-1',
    companyId: 'demo-company-1',
    responses: {
      q1: 9,
      q2: 'Customer Support',
      q3: true,
      q4: 'Great service, very responsive team! The product has exceeded our expectations.',
    },
    score: 9,
    submittedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[0],
    company: demoCompanies[0],
  },
  {
    id: 'demo-response-2',
    surveyId: 'demo-survey-1',
    contactId: 'demo-contact-2',
    companyId: 'demo-company-2',
    responses: {
      q1: 7,
      q2: 'Product Quality',
      q3: true,
      q4: 'Would appreciate faster response times on support tickets.',
    },
    score: 7,
    submittedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[1],
    company: demoCompanies[1],
  },
  {
    id: 'demo-response-3',
    surveyId: 'demo-survey-1',
    contactId: 'demo-contact-3',
    companyId: 'demo-company-3',
    responses: {
      q1: 10,
      q2: 'Ease of Use',
      q3: true,
      q4: 'Absolutely love the product! Best CRM we have used.',
    },
    score: 10,
    submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[2],
    company: demoCompanies[2],
  },
  // Onboarding Survey Responses
  {
    id: 'demo-response-4',
    surveyId: 'demo-survey-2',
    contactId: 'demo-contact-5',
    companyId: 'demo-company-1',
    responses: {
      q1: 5,
      q2: 4,
      q3: true,
      q4: 'Live Training Sessions',
      q5: 'The training materials were very helpful. Would love more video content.',
    },
    score: 9,
    submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[4],
    company: demoCompanies[0],
  },
  {
    id: 'demo-response-5',
    surveyId: 'demo-survey-2',
    contactId: 'demo-contact-2',
    companyId: 'demo-company-2',
    responses: {
      q1: 4,
      q2: 5,
      q3: true,
      q4: 'Documentation',
      q5: 'Documentation was comprehensive and easy to follow.',
    },
    score: 9,
    submittedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[1],
    company: demoCompanies[1],
  },
  // Support Survey Responses
  {
    id: 'demo-response-6',
    surveyId: 'demo-survey-3',
    contactId: 'demo-contact-1',
    companyId: 'demo-company-1',
    responses: {
      q1: 6,
      q2: true,
      q3: 5,
      q4: 'Live Chat',
      q5: 'Quick resolution through live chat. Very impressed!',
    },
    score: 8.5,
    submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[0],
    company: demoCompanies[0],
  },
  {
    id: 'demo-response-7',
    surveyId: 'demo-survey-3',
    contactId: 'demo-contact-3',
    companyId: 'demo-company-3',
    responses: {
      q1: 5,
      q2: true,
      q3: 4,
      q4: 'Email',
      q5: 'Issue was resolved within 24 hours. Good turnaround time.',
    },
    score: 7,
    submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[2],
    company: demoCompanies[2],
  },
  // Product Feedback Survey Responses
  {
    id: 'demo-response-8',
    surveyId: 'demo-survey-4',
    contactId: 'demo-contact-1',
    companyId: 'demo-company-1',
    responses: {
      q1: 9,
      q2: 'Dashboard Analytics',
      q3: false,
      q4: 'AI Insights',
      q5: 'Would love to see more predictive analytics and AI-powered recommendations.',
    },
    score: 9,
    submittedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[0],
    company: demoCompanies[0],
  },
  {
    id: 'demo-response-9',
    surveyId: 'demo-survey-4',
    contactId: 'demo-contact-4',
    companyId: 'demo-company-2',
    responses: {
      q1: 8,
      q2: 'Deal Management',
      q3: true,
      q4: 'Mobile App',
      q5: 'A mobile app would be game-changing for our sales team in the field.',
    },
    score: 8,
    submittedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    contact: demoContacts[3],
    company: demoCompanies[1],
  },
];

// =====================
// Phase 4: Health Scores
// Health scores are calculated from survey responses
// NPS: from demo-survey-1 responses
// CSAT: from demo-survey-2 responses
// CES: from demo-survey-3 responses
// =====================
export const demoHealthScores = [
  {
    id: 'demo-health-1',
    companyId: 'demo-company-1',
    contactId: null,
    score: 88,
    npsScore: 9, // From response-1 (q1: 9)
    csatScore: 4.5, // From response-4 (avg of q1:5, q2:4)
    cesScore: 8.5, // From response-6 (normalized)
    engagementScore: 92,
    riskLevel: 'excellent',
    factors: {
      surveyParticipation: 'high',
      recentActivity: 'very_active',
      supportTicketTrend: 'improving',
      productUsage: 'power_user',
    },
    lastSurveyResponse: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    calculatedAt: new Date().toISOString(),
    company: demoCompanies[0],
  },
  {
    id: 'demo-health-2',
    companyId: 'demo-company-2',
    contactId: null,
    score: 72,
    npsScore: 7, // From response-2 (q1: 7)
    csatScore: 4.5, // From response-5 (avg of q1:4, q2:5)
    cesScore: null,
    engagementScore: 68,
    riskLevel: 'good',
    factors: {
      surveyParticipation: 'medium',
      recentActivity: 'active',
      supportTicketTrend: 'stable',
      productUsage: 'regular',
    },
    lastSurveyResponse: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    calculatedAt: new Date().toISOString(),
    company: demoCompanies[1],
  },
  {
    id: 'demo-health-3',
    companyId: 'demo-company-3',
    contactId: null,
    score: 78,
    npsScore: 10, // From response-3 (q1: 10)
    csatScore: null,
    cesScore: 7, // From response-7 (normalized)
    engagementScore: 72,
    riskLevel: 'good',
    factors: {
      surveyParticipation: 'medium',
      recentActivity: 'active',
      supportTicketTrend: 'stable',
      productUsage: 'regular',
    },
    lastSurveyResponse: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    calculatedAt: new Date().toISOString(),
    company: demoCompanies[2],
  },
];

// =====================
// Phase 4: Automations
// =====================
export const demoAutomations = [
  {
    id: 'demo-automation-1',
    name: 'Welcome Email on Deal Won',
    triggerType: 'event',
    triggerConditions: {
      event: 'deal.stage_changed',
      toStage: 'Closed Won',
    },
    actions: [
      { type: 'start_sequence', sequenceId: 'demo-sequence-1' },
      { type: 'create_task', title: 'Schedule onboarding kickoff', assignTo: 'owner' },
    ],
    status: 'active',
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-automation-2',
    name: 'NPS Survey After Go-Live',
    triggerType: 'event',
    triggerConditions: {
      event: 'milestone.completed',
      milestoneName: 'Go Live',
    },
    actions: [
      { type: 'send_survey', surveyId: 'demo-survey-1', delay: '7d' },
    ],
    status: 'active',
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-automation-3',
    name: 'At-Risk Customer Alert',
    triggerType: 'event',
    triggerConditions: {
      event: 'health_score.below_threshold',
      threshold: 50,
    },
    actions: [
      { type: 'create_task', title: 'Review at-risk customer', assignTo: 'owner', priority: 'high' },
      { type: 'notify', channel: 'email', recipients: ['account_manager'] },
    ],
    status: 'active',
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-automation-4',
    name: 'Ticket SLA Warning',
    triggerType: 'time',
    triggerConditions: {
      entity: 'ticket',
      condition: 'due_date_approaching',
      hours: 24,
    },
    actions: [
      { type: 'notify', channel: 'email', recipients: ['assignee'] },
    ],
    status: 'active',
    createdBy: 'demo-user-id',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// =====================
// Demo Emails (sent)
// =====================
export const demoEmails = [
  {
    id: 'demo-email-1',
    toEmail: 'john.smith@acme.com',
    subject: 'Welcome to Our Platform, John!',
    body: 'Dear John,\n\nWelcome aboard! We\'re excited to have Acme Corporation as our newest customer.\n\nYour dedicated account manager will reach out within 24 hours to schedule your onboarding kickoff.\n\nBest regards,\nThe Team',
    templateId: 'demo-template-1',
    contactId: 'demo-contact-1',
    dealId: 'demo-deal-4',
    sentBy: 'demo-user-id',
    sentAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    openedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 3600000).toISOString(),
    clickedAt: null,
    responseReceived: true,
    contact: demoContacts[0],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-email-2',
    toEmail: 'john.smith@acme.com',
    subject: 'Your Onboarding Checklist - Acme Corporation',
    body: 'Hi John,\n\nHere\'s your onboarding checklist:\n\n1. Complete documentation\n2. Schedule training sessions\n3. Review system configuration\n4. Test integrations\n\nLet us know if you have any questions!\n\nBest,\nThe Team',
    templateId: 'demo-template-2',
    contactId: 'demo-contact-1',
    dealId: null,
    sentBy: 'demo-user-id',
    sentAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    openedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000 + 7200000).toISOString(),
    clickedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000 + 7800000).toISOString(),
    responseReceived: false,
    contact: demoContacts[0],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Update dashboard stats to include new metrics
export const demoDashboardStats = {
  // Sales metrics
  pipelineValue: 220000,
  wonDealsValue: 80000,
  lostDealsValue: 35000,
  wonDealsCount: 1,
  lostDealsCount: 1,
  winRate: 50,
  // Entity counts
  totalCompanies: 3,
  totalContacts: 5,
  totalDeals: 5,
  totalTasks: 4,
  totalProjects: 20,
  totalTickets: 4,
  // Task metrics
  upcomingTasksCount: 3,
  overdueTasksCount: 0,
  // Ticket metrics
  openTicketsCount: 2,
  resolvedTicketsCount: 1,
  avgTicketResolutionHours: 48,
  // Health metrics
  avgHealthScore: 65,
  atRiskCustomers: 1,
  // Survey metrics
  avgNpsScore: 8,
  npsPromoters: 1,
  npsPassives: 1,
  npsDetractors: 0,
  surveyResponseRate: 60,
};
